### ISSUE TITLE
Display products from Rest API

### ISSUE THREAD

**Issue by GonzaloSaad** [guppys-org/guppy-backend#1]
## Scope
- Return a list of `Product` filtering by `businessId`

## Tasks
---

### Spring based
- [ ] Add Controller for `/v1/products`
- [ ] Add Service for `products`
     - Return nothing initially

### Hibernate based
- [ ] Create DB objets for `Products` 
- [ ] Add Repository for `Products`

### Filtering Logic
- [ ] Allow filtering by `businessId`

## Dev Notes
- Testing will be done with mocked data
