### ISSUE TITLE
Allow filtering by businessId to /v1/products

### ISSUE THREAD

**Issue by pedro9747** [guppys-org/guppy-backend#25]
## Context
We need to filter by `businessID` in `/v1/products` to get all the products that a business offers. 

## Acceptance Criteria

**Given** a `businessID`
**And** a list of products
**When** GET is executed on `/v1/products`
**And** the query parameter is present
**Then** a list of products is retrieved
**And** the product's `businessID` is equal to the one in the query

## Tasks

- [ ] Add a new [query parameter](https://rapidapi.com/blog/api-glossary/parameters/query/) 
- [ ] Modify the existing `getProducts` method in `ProductsService` to allow filtering. 
- [ ] Adapt / Extend all needed tests to get 100% coverage

## Dev Notes
- An example of using query parameters in spring can be checked [here](https://www.baeldung.com/spring-request-param).
