### ISSUE TITLE
Add POST /v1/products

### ISSUE THREAD

**Issue by pedro9747** [guppys-org/guppy-backend#30]
## Context
We need an endpoint for creating a new product for a business

## Acceptance Criteria

_Scenario 1: Success - Product Created_
**Given** a valid body
**When** POST is executed on `/v1/products`
**And** the body is present
**Then** a new product is created in the DB
**And** the response status code is 201
**And** the product is returned in the response body

_Scenario 2: Invalid Payload_
**Given** an invalid body
**When** POST is executed on `/v1/products`
**And** the body is present
**Then** the response status code is 400

## Tasks

- [ ] Add a POST mapping in ProductController
- [ ] Add a new method in ProductService for `createProduct(...)`
- [ ] Add Unit Test for Controller and Service

## Dev Notes
- The valid body structure: 
```json
{
   "id": "cc6b7742-e811-4630-962b-d794db7eedf4",
   "name":"Some Product Name",
   "price":125.50,
   "business_id":"16b9ba48-309d-4a83-ba9c-56bb768a0bf7",
   "image_url":"some_url"
}
```
- Doc about [responses](https://jsonapi.org/format/#crud-creating-responses-201) when creating objects
- Doc about requests [body](https://www.baeldung.com/spring-request-response-body#requestbody) in Spring
- How to [validate](https://reflectoring.io/bean-validation-with-spring-boot/) requests body in spring. 
- Exception [handlers](https://www.baeldung.com/spring-boot-bean-validation) can be useful.
